name: rest_test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^2.0.0
  # Splash Screen
  flutter_native_splash: ^2.4.0
  # Dotenv
  flutter_dotenv: ^5.1.0

  # Localization And Logger
  intl: ^0.19.0
  logger: ^2.1.0

  # GetX
  get: ^4.6.6

  # flutter_secure_storage
  flutter_secure_storage: ^9.0.0

  # Svg
  flutter_svg: ^2.0.17

  # Cached Network Image
  cached_network_image: ^3.3.1

  # progress_bar
  linear_progress_bar: ^1.1.3

  # fl_chart
  fl_chart: ^0.66.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  characters: ^1.2.1

  # kakao oauth
  kakao_flutter_sdk: ^1.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

  # app icon
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: AppleSDGothicNeoExtraBold
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo-ExtraBold.ttf
    - family: AppleSDGothicNeoBold
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo-Bold.ttf
    - family: AppleSDGothicNeoSemiBold
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo-SemiBold.ttf
    - family: AppleSDGothicNeoMedium
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo-Medium.ttf
    - family: AppleSDGothicNeoRegular
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo-Regular.ttf
    - family: AppleSDGothicNeoLight
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo-Light.ttf

  assets:
    - assets/icons/
    - assets/icons/bottom_navigation/
    - assets/icons/appbar/
    - assets/icons/test/
    - assets/images/
    - assets/config/
    - assets/fonts/
    - assets/config/.env
